{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Jun 27 01:15:39 2013) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",856,64,700,500);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(-0.3658228,-23.10127,2.54557,27.53165);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.05);
   c1->SetTopMargin(0.05);
   c1->SetBottomMargin(0.16);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   Double_t xAxis17[10] = {0.1, 0.35, 0.6, 0.8, 1.05, 1.3, 1.55, 1.85, 2.1, 2.4}; 
   
   TH1F *hTriggerAbsoluteSystSumSqEtaPlus = new TH1F("hTriggerAbsoluteSystSumSqEtaPlus","hTriggerAbsoluteSystSumSqEtaPlus",9, xAxis17);
   hTriggerAbsoluteSystSumSqEtaPlus->SetBinError(1,4.56216);
   hTriggerAbsoluteSystSumSqEtaPlus->SetBinError(2,5.710156);
   hTriggerAbsoluteSystSumSqEtaPlus->SetBinError(3,5.057665);
   hTriggerAbsoluteSystSumSqEtaPlus->SetBinError(4,5.998048);
   hTriggerAbsoluteSystSumSqEtaPlus->SetBinError(5,11.73691);
   hTriggerAbsoluteSystSumSqEtaPlus->SetBinError(6,8.336235);
   hTriggerAbsoluteSystSumSqEtaPlus->SetBinError(7,5.72013);
   hTriggerAbsoluteSystSumSqEtaPlus->SetBinError(8,7.492759);
   hTriggerAbsoluteSystSumSqEtaPlus->SetBinError(9,9.922767);
   hTriggerAbsoluteSystSumSqEtaPlus->SetMinimum(-15);
   hTriggerAbsoluteSystSumSqEtaPlus->SetMaximum(25);
   hTriggerAbsoluteSystSumSqEtaPlus->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#00ffff");
   hTriggerAbsoluteSystSumSqEtaPlus->SetFillColor(ci);
   hTriggerAbsoluteSystSumSqEtaPlus->SetLineWidth(2);
   hTriggerAbsoluteSystSumSqEtaPlus->SetMarkerStyle(20);
   hTriggerAbsoluteSystSumSqEtaPlus->SetMarkerSize(1.2);
   hTriggerAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitle("|#eta|");
   hTriggerAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelFont(42);
   hTriggerAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelSize(0.05);
   hTriggerAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleSize(0.05);
   hTriggerAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleOffset(1.4);
   hTriggerAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleFont(42);
   hTriggerAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitle("Systematic Uncertainties[%]");
   hTriggerAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelFont(42);
   hTriggerAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelSize(0.05);
   hTriggerAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleSize(0.05);
   hTriggerAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleOffset(1.4);
   hTriggerAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleFont(42);
   hTriggerAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelFont(42);
   hTriggerAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelSize(0.05);
   hTriggerAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleSize(0.05);
   hTriggerAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleFont(42);
   hTriggerAbsoluteSystSumSqEtaPlus->Draw("e2");
   Double_t xAxis18[10] = {0.1, 0.35, 0.6, 0.8, 1.05, 1.3, 1.55, 1.85, 2.1, 2.4}; 
   
   TH1F *hPtResolAbsoluteSystSumSqEtaPlus = new TH1F("hPtResolAbsoluteSystSumSqEtaPlus","hPtResolAbsoluteSystSumSqEtaPlus",9, xAxis18);
   hPtResolAbsoluteSystSumSqEtaPlus->SetBinError(1,4.545979);
   hPtResolAbsoluteSystSumSqEtaPlus->SetBinError(2,5.697069);
   hPtResolAbsoluteSystSumSqEtaPlus->SetBinError(3,5.041911);
   hPtResolAbsoluteSystSumSqEtaPlus->SetBinError(4,5.985519);
   hPtResolAbsoluteSystSumSqEtaPlus->SetBinError(5,11.73043);
   hPtResolAbsoluteSystSumSqEtaPlus->SetBinError(6,8.326667);
   hPtResolAbsoluteSystSumSqEtaPlus->SetBinError(7,5.705213);
   hPtResolAbsoluteSystSumSqEtaPlus->SetBinError(8,7.481627);
   hPtResolAbsoluteSystSumSqEtaPlus->SetBinError(9,9.914731);
   hPtResolAbsoluteSystSumSqEtaPlus->SetStats(0);

   ci = TColor::GetColor("#99ffff");
   hPtResolAbsoluteSystSumSqEtaPlus->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   hPtResolAbsoluteSystSumSqEtaPlus->SetLineColor(ci);
   hPtResolAbsoluteSystSumSqEtaPlus->SetLineWidth(2);
   hPtResolAbsoluteSystSumSqEtaPlus->SetMarkerStyle(20);
   hPtResolAbsoluteSystSumSqEtaPlus->SetMarkerSize(1.2);
   hPtResolAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelFont(42);
   hPtResolAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelSize(0.05);
   hPtResolAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleSize(0.05);
   hPtResolAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleOffset(1.4);
   hPtResolAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleFont(42);
   hPtResolAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelFont(42);
   hPtResolAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelSize(0.05);
   hPtResolAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleSize(0.05);
   hPtResolAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleOffset(1.4);
   hPtResolAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleFont(42);
   hPtResolAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelFont(42);
   hPtResolAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelSize(0.05);
   hPtResolAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleSize(0.05);
   hPtResolAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleFont(42);
   hPtResolAbsoluteSystSumSqEtaPlus->Draw("e2same");
   Double_t xAxis19[10] = {0.1, 0.35, 0.6, 0.8, 1.05, 1.3, 1.55, 1.85, 2.1, 2.4}; 
   
   TH1F *hMuonRecoAbsoluteSystSumSqEtaPlus = new TH1F("hMuonRecoAbsoluteSystSumSqEtaPlus","hMuonRecoAbsoluteSystSumSqEtaPlus",9, xAxis19);
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetBinError(1,4.362158);
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetBinError(2,5.549587);
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetBinError(3,4.863439);
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetBinError(4,5.844512);
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetBinError(5,11.65814);
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetBinError(6,8.2196);
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetBinError(7,5.53676);
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetBinError(8,7.356802);
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetBinError(9,9.825005);
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetStats(0);

   ci = TColor::GetColor("#ff99ff");
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetLineColor(ci);
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetLineWidth(2);
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetMarkerStyle(20);
   hMuonRecoAbsoluteSystSumSqEtaPlus->SetMarkerSize(1.2);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelFont(42);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelSize(0.05);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleSize(0.05);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleOffset(1.4);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleFont(42);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelFont(42);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelSize(0.05);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleSize(0.05);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleOffset(1.4);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleFont(42);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelFont(42);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelSize(0.05);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleSize(0.05);
   hMuonRecoAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleFont(42);
   hMuonRecoAbsoluteSystSumSqEtaPlus->Draw("e2same");
   Double_t xAxis20[10] = {0.1, 0.35, 0.6, 0.8, 1.05, 1.3, 1.55, 1.85, 2.1, 2.4}; 
   
   TH1F *hTrackingAbsoluteSystSumSqEtaPlus = new TH1F("hTrackingAbsoluteSystSumSqEtaPlus","hTrackingAbsoluteSystSumSqEtaPlus",9, xAxis20);
   hTrackingAbsoluteSystSumSqEtaPlus->SetBinError(1,4.229807);
   hTrackingAbsoluteSystSumSqEtaPlus->SetBinError(2,5.444818);
   hTrackingAbsoluteSystSumSqEtaPlus->SetBinError(3,4.735543);
   hTrackingAbsoluteSystSumSqEtaPlus->SetBinError(4,5.744554);
   hTrackingAbsoluteSystSumSqEtaPlus->SetBinError(5,11.60768);
   hTrackingAbsoluteSystSumSqEtaPlus->SetBinError(6,8.14442);
   hTrackingAbsoluteSystSumSqEtaPlus->SetBinError(7,5.416698);
   hTrackingAbsoluteSystSumSqEtaPlus->SetBinError(8,7.268856);
   hTrackingAbsoluteSystSumSqEtaPlus->SetBinError(9,9.76221);
   hTrackingAbsoluteSystSumSqEtaPlus->SetStats(0);

   ci = TColor::GetColor("#ff9999");
   hTrackingAbsoluteSystSumSqEtaPlus->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   hTrackingAbsoluteSystSumSqEtaPlus->SetLineColor(ci);
   hTrackingAbsoluteSystSumSqEtaPlus->SetLineWidth(2);
   hTrackingAbsoluteSystSumSqEtaPlus->SetMarkerStyle(20);
   hTrackingAbsoluteSystSumSqEtaPlus->SetMarkerSize(1.2);
   hTrackingAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelFont(42);
   hTrackingAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelSize(0.05);
   hTrackingAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleSize(0.05);
   hTrackingAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleOffset(1.4);
   hTrackingAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleFont(42);
   hTrackingAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelFont(42);
   hTrackingAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelSize(0.05);
   hTrackingAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleSize(0.05);
   hTrackingAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleOffset(1.4);
   hTrackingAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleFont(42);
   hTrackingAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelFont(42);
   hTrackingAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelSize(0.05);
   hTrackingAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleSize(0.05);
   hTrackingAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleFont(42);
   hTrackingAbsoluteSystSumSqEtaPlus->Draw("e2same");
   Double_t xAxis21[10] = {0.1, 0.35, 0.6, 0.8, 1.05, 1.3, 1.55, 1.85, 2.1, 2.4}; 
   
   TH1F *hCwAbsoluteSystSumSqEtaPlus = new TH1F("hCwAbsoluteSystSumSqEtaPlus","hCwAbsoluteSystSumSqEtaPlus",9, xAxis21);
   hCwAbsoluteSystSumSqEtaPlus->SetBinError(1,4.142884);
   hCwAbsoluteSystSumSqEtaPlus->SetBinError(2,5.376695);
   hCwAbsoluteSystSumSqEtaPlus->SetBinError(3,4.651846);
   hCwAbsoluteSystSumSqEtaPlus->SetBinError(4,5.679658);
   hCwAbsoluteSystSumSqEtaPlus->SetBinError(5,11.57527);
   hCwAbsoluteSystSumSqEtaPlus->SetBinError(6,8.095938);
   hCwAbsoluteSystSumSqEtaPlus->SetBinError(7,5.338442);
   hCwAbsoluteSystSumSqEtaPlus->SetBinError(8,7.212009);
   hCwAbsoluteSystSumSqEtaPlus->SetBinError(9,9.721809);
   hCwAbsoluteSystSumSqEtaPlus->SetStats(0);

   ci = TColor::GetColor("#ffff99");
   hCwAbsoluteSystSumSqEtaPlus->SetFillColor(ci);
   hCwAbsoluteSystSumSqEtaPlus->SetLineWidth(2);
   hCwAbsoluteSystSumSqEtaPlus->SetMarkerStyle(20);
   hCwAbsoluteSystSumSqEtaPlus->SetMarkerSize(1.2);
   hCwAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelFont(42);
   hCwAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelSize(0.05);
   hCwAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleSize(0.05);
   hCwAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleOffset(1.4);
   hCwAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleFont(42);
   hCwAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelFont(42);
   hCwAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelSize(0.05);
   hCwAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleSize(0.05);
   hCwAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleOffset(1.4);
   hCwAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleFont(42);
   hCwAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelFont(42);
   hCwAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelSize(0.05);
   hCwAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleSize(0.05);
   hCwAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleFont(42);
   hCwAbsoluteSystSumSqEtaPlus->Draw("e2same");
   Double_t xAxis22[10] = {0.1, 0.35, 0.6, 0.8, 1.05, 1.3, 1.55, 1.85, 2.1, 2.4}; 
   
   TH1F *hMPTResolAbsoluteSystSumSqEtaPlus = new TH1F("hMPTResolAbsoluteSystSumSqEtaPlus","hMPTResolAbsoluteSystSumSqEtaPlus",9, xAxis22);
   hMPTResolAbsoluteSystSumSqEtaPlus->SetBinError(1,4.030074);
   hMPTResolAbsoluteSystSumSqEtaPlus->SetBinError(2,5.195527);
   hMPTResolAbsoluteSystSumSqEtaPlus->SetBinError(3,4.398353);
   hMPTResolAbsoluteSystSumSqEtaPlus->SetBinError(4,5.328365);
   hMPTResolAbsoluteSystSumSqEtaPlus->SetBinError(5,11.26682);
   hMPTResolAbsoluteSystSumSqEtaPlus->SetBinError(6,7.578392);
   hMPTResolAbsoluteSystSumSqEtaPlus->SetBinError(7,3.782341);
   hMPTResolAbsoluteSystSumSqEtaPlus->SetBinError(8,5.89492);
   hMPTResolAbsoluteSystSumSqEtaPlus->SetBinError(9,8.724849);
   hMPTResolAbsoluteSystSumSqEtaPlus->SetStats(0);

   ci = TColor::GetColor("#cc99ff");
   hMPTResolAbsoluteSystSumSqEtaPlus->SetFillColor(ci);
   hMPTResolAbsoluteSystSumSqEtaPlus->SetLineWidth(2);
   hMPTResolAbsoluteSystSumSqEtaPlus->SetMarkerStyle(20);
   hMPTResolAbsoluteSystSumSqEtaPlus->SetMarkerSize(1.2);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelFont(42);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelSize(0.05);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleSize(0.05);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleOffset(1.4);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleFont(42);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelFont(42);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelSize(0.05);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleSize(0.05);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleOffset(1.4);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleFont(42);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelFont(42);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelSize(0.05);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleSize(0.05);
   hMPTResolAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleFont(42);
   hMPTResolAbsoluteSystSumSqEtaPlus->Draw("e2same");
   Double_t xAxis23[10] = {0.1, 0.35, 0.6, 0.8, 1.05, 1.3, 1.55, 1.85, 2.1, 2.4}; 
   
   TH1F *hIsolationAbsoluteSystSumSqEtaPlus = new TH1F("hIsolationAbsoluteSystSumSqEtaPlus","hIsolationAbsoluteSystSumSqEtaPlus",9, xAxis23);
   hIsolationAbsoluteSystSumSqEtaPlus->SetBinError(1,1.982788);
   hIsolationAbsoluteSystSumSqEtaPlus->SetBinError(2,2.486452);
   hIsolationAbsoluteSystSumSqEtaPlus->SetBinError(3,2.016804);
   hIsolationAbsoluteSystSumSqEtaPlus->SetBinError(4,2.004129);
   hIsolationAbsoluteSystSumSqEtaPlus->SetBinError(5,2.959311);
   hIsolationAbsoluteSystSumSqEtaPlus->SetBinError(6,2.465108);
   hIsolationAbsoluteSystSumSqEtaPlus->SetBinError(7,1.469091);
   hIsolationAbsoluteSystSumSqEtaPlus->SetBinError(8,1.807734);
   hIsolationAbsoluteSystSumSqEtaPlus->SetBinError(9,1.94881);
   hIsolationAbsoluteSystSumSqEtaPlus->SetStats(0);

   ci = TColor::GetColor("#9999ff");
   hIsolationAbsoluteSystSumSqEtaPlus->SetFillColor(ci);
   hIsolationAbsoluteSystSumSqEtaPlus->SetLineWidth(2);
   hIsolationAbsoluteSystSumSqEtaPlus->SetMarkerStyle(20);
   hIsolationAbsoluteSystSumSqEtaPlus->SetMarkerSize(1.2);
   hIsolationAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelFont(42);
   hIsolationAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelSize(0.05);
   hIsolationAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleSize(0.05);
   hIsolationAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleOffset(1.4);
   hIsolationAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleFont(42);
   hIsolationAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelFont(42);
   hIsolationAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelSize(0.05);
   hIsolationAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleSize(0.05);
   hIsolationAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleOffset(1.4);
   hIsolationAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleFont(42);
   hIsolationAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelFont(42);
   hIsolationAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelSize(0.05);
   hIsolationAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleSize(0.05);
   hIsolationAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleFont(42);
   hIsolationAbsoluteSystSumSqEtaPlus->Draw("e2same");
   Double_t xAxis24[10] = {0.1, 0.35, 0.6, 0.8, 1.05, 1.3, 1.55, 1.85, 2.1, 2.4}; 
   
   TH1F *hBkgSubtractionAbsoluteSystSumSqEtaPlus = new TH1F("hBkgSubtractionAbsoluteSystSumSqEtaPlus","hBkgSubtractionAbsoluteSystSumSqEtaPlus",9, xAxis24);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetBinError(1,1.58167);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetBinError(2,1.607778);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetBinError(3,1.245031);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetBinError(4,1.604424);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetBinError(5,2.017487);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetBinError(6,1.59861);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetBinError(7,0.8737755);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetBinError(8,0.7117232);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetBinError(9,0.9369362);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetStats(0);

   ci = TColor::GetColor("#99ff99");
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetFillColor(ci);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetLineWidth(2);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetMarkerStyle(20);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->SetMarkerSize(1.2);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelFont(42);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetXaxis()->SetLabelSize(0.05);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleSize(0.05);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleOffset(1.4);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetXaxis()->SetTitleFont(42);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelFont(42);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetYaxis()->SetLabelSize(0.05);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleSize(0.05);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleOffset(1.4);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetYaxis()->SetTitleFont(42);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelFont(42);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetZaxis()->SetLabelSize(0.05);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleSize(0.05);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->GetZaxis()->SetTitleFont(42);
   hBkgSubtractionAbsoluteSystSumSqEtaPlus->Draw("e2same");
   
   TLegend *leg = new TLegend(0.1724138,0.690678,0.4425287,0.9279661,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("hBkgSubtractionAbsoluteSystSumSqEtaPlus","Background Subtraction","fe");

   ci = TColor::GetColor("#99ff99");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("hIsolationAbsoluteSystSumSqEtaPlus","Isolation","fe");

   ci = TColor::GetColor("#9999ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry=leg->AddEntry("hMPTResolAbsoluteSystSumSqEtaPlus","#slash{p_{T}} Resolution","fe");

   ci = TColor::GetColor("#cc99ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry=leg->AddEntry("hCwAbsoluteSystSumSqEtaPlus","C_{W}","fe");

   ci = TColor::GetColor("#ffff99");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   leg = new TLegend(0.1724138,0.690678,0.4425287,0.9279661,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("hBkgSubtractionAbsoluteSystSumSqEtaPlus","Background Subtraction","fe");

   ci = TColor::GetColor("#99ff99");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("hIsolationAbsoluteSystSumSqEtaPlus","Isolation","fe");

   ci = TColor::GetColor("#9999ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry=leg->AddEntry("hMPTResolAbsoluteSystSumSqEtaPlus","#slash{p_{T}} Resolution","fe");

   ci = TColor::GetColor("#cc99ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry=leg->AddEntry("hCwAbsoluteSystSumSqEtaPlus","C_{W}","fe");

   ci = TColor::GetColor("#ffff99");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   leg = new TLegend(0.1724138,0.690678,0.4425287,0.9279661,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("hBkgSubtractionAbsoluteSystSumSqEtaPlus","Background Subtraction","fe");

   ci = TColor::GetColor("#99ff99");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("hIsolationAbsoluteSystSumSqEtaPlus","Isolation","fe");

   ci = TColor::GetColor("#9999ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry=leg->AddEntry("hMPTResolAbsoluteSystSumSqEtaPlus","#slash{p_{T}} Resolution","fe");

   ci = TColor::GetColor("#cc99ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry=leg->AddEntry("hCwAbsoluteSystSumSqEtaPlus","C_{W}","fe");

   ci = TColor::GetColor("#ffff99");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   leg = new TLegend(0.5890805,0.7076271,0.8591954,0.934322,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("hTrackingAbsoluteSystSumSqEtaPlus","Tracking","fe");

   ci = TColor::GetColor("#ff9999");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("hMuonRecoAbsoluteSystSumSqEtaPlus","Muon reconstruction","fe");

   ci = TColor::GetColor("#ff99ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("hPtResolAbsoluteSystSumSqEtaPlus","p_{T}^{#mu} resolution","fe");

   ci = TColor::GetColor("#99ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("hTriggerAbsoluteSystSumSqEtaPlus","Trigger","fe");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.3045977,0.2351695,"#mu^{+}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
