/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSHIFTEDKEYSPDF
#define ROOSHIFTEDKEYSPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

#include <iostream>
 
class RooShiftedKeysPdf : public RooAbsPdf {
public:
  RooShiftedKeysPdf() {} ; 
  RooShiftedKeysPdf(const char *name, const char *title, RooAbsReal& x, RooAbsPdf& keysPdf, RooAbsReal& shift, RooAbsReal& stretch) ;
  RooShiftedKeysPdf(const RooShiftedKeysPdf& other, const char* name=0) ;

  virtual TObject* clone(const char* newname) const { return new RooShiftedKeysPdf(*this,newname); }
  inline virtual ~RooShiftedKeysPdf() { }
  //inline virtual ~RooShiftedKeysPdf() ;
  Double_t evaluate() const;
  
protected:

  mutable RooRealProxy    m_xProxy;
  mutable RooRealVar*     m_x;
  RooAbsPdf*              m_keysPdf;
  RooRealProxy            m_shift;
  RooRealProxy            m_stretch;
    
  double                  m_minValX;
  double                  m_maxValX;
  double                  m_mean;
  
  //Double_t evaluate() const;
  Double_t getMean() const;

private:

  ClassDef(RooShiftedKeysPdf,1) // Your description goes here...
};
 
#endif
